"""add set attendances

The durable half of "acts you saw": one row per (user, set) once the user has
dwelled inside that stage's geofence long enough while the set was live. No
coordinates — positions stay in Redis (see app/attendance.py).

Revision ID: 972fb8173597
Revises: 29fa5cd32665
Create Date: 2026-07-29 22:21:57.923369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972fb8173597'
down_revision: Union[str, Sequence[str], None] = '29fa5cd32665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_attendances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('set_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_id', name='uq_set_attendance_user_set')
    )
    op.create_index(op.f('ix_set_attendances_event_id'), 'set_attendances', ['event_id'], unique=False)
    op.create_index(op.f('ix_set_attendances_set_id'), 'set_attendances', ['set_id'], unique=False)
    op.create_index(op.f('ix_set_attendances_user_id'), 'set_attendances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_attendances_user_id'), table_name='set_attendances')
    op.drop_index(op.f('ix_set_attendances_set_id'), table_name='set_attendances')
    op.drop_index(op.f('ix_set_attendances_event_id'), table_name='set_attendances')
    op.drop_table('set_attendances')
    # ### end Alembic commands ###
